[project]
name = "djangosrh"
version = "0.1.0"
description = "Add your description here"
readme = "README.org"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.1",
    "pillow>=12.1.0",
    "psycopg2-binary>=2.9.11",
    "qrcode>=8.2",
]
